

#define LIS3MDL_ADDRESS          (0x38 >> 1)
#define LIS3MDL_REGISTER_WHO_AM_I   0x0F
#define LIS3MDL_REGISTER_CTRL1      0x20
#define LIS3MDL_REGISTER_CTRL2      0x21
#define LIS3MDL_REGISTER_CTRL3      0x22
#define LIS3MDL_REGISTER_CTRL4      0x23
#define LIS3MDL_REGISTER_CTRL5      0x24
#define LIS3MDL_REGISTER_STATUS     0x27
#define LIS3MDL_REGISTER_OUT_X_L    0x28
#define LIS3MDL_REGISTER_OUT_X_H    0x29
#define LIS3MDL_REGISTER_OUT_Y_L    0x2A
#define LIS3MDL_REGISTER_OUT_Y_H    0x2B
#define LIS3MDL_REGISTER_OUT_Z_L    0x2C
#define LIS3MDL_REGISTER_OUT_Z_H    0x2D

#define LIS3MDL_WHO_I_AM	0x3D

